spring.application.name=secure_payment_network

spring.docker.compose.file=compose.yaml
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://localhost:5432/mydatabase
spring.flyway.user=myuser
spring.flyway.password=secret
